version: '3.3'

networks:
  aw-network:
    driver: bridge

volumes:
  zipkin_data:
  prometheus_data:
  grafana_data:

services:
  zipkin:
    image: openzipkin/zipkin:latest
    networks:
      - aw-network
    ports:
      - "9411:9411"
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - aw-network
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    networks:
      - aw-network
    ports:
      - "3000:3000"