server:
  port: 8081

spring:
  application:
    name: app-open-feign-observability

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"

logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

client:
  observability:
    uri: http://localhost:8080